{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openshift-cluster-health-mcp.fullname" . }}-reader
  labels:
    {{- include "openshift-cluster-health-mcp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "openshift-cluster-health-mcp.fullname" . }}-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "openshift-cluster-health-mcp.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
